import { Response } from 'express';
import { aiService } from './ai.service';
import { goalService } from '../goal/goal.service';
import { taskService } from '../task/task.service';
import { plannerService } from '../planner/planner.service';
import { asyncHandler } from '../../utils/asyncHandler';
import { ApiResponse } from '../../utils/ApiResponse';
import { AuthRequest } from '../../middleware/auth.middleware';
import { Goal } from '../goal/goal.model';
import { Task } from '../task/task.model';
import { User } from '../user/user.model';

export const aiController = {
  analyzeGoal: asyncHandler(async (req: AuthRequest, res: Response) => {
    const { goalText, deadline } = req.body;
    const analysis = await aiService.analyzeGoal(goalText, deadline);
    res.json(ApiResponse.success(analysis, 'Goal analyzed'));
  }),

  generateTasks: asyncHandler(async (req: AuthRequest, res: Response) => {
    const { goalId } = req.body;
    const goal = await goalService.getById(goalId, req.userId!);
    const user = await User.findById(req.userId!);
    const hoursPerDay = user?.preferences?.workingHoursPerDay || 8;

    // If goal has no AI analysis, analyze it first
    let complexity = goal.aiAnalysis?.complexity || 'medium';
    if (!goal.aiAnalysis) {
      const analysis = await aiService.analyzeGoal(
        `${goal.title}: ${goal.description}`,
        goal.deadline.toISOString()
      );
      goal.aiAnalysis = analysis;
      await goal.save();
      complexity = analysis.complexity;
    }

    const tasks = await aiService.generateTasks(
      goal.title,
      goal.description,
      goal.deadline.toISOString(),
      complexity,
      hoursPerDay
    );

    // Save the generated tasks to the database
    const savedTasks = await taskService.bulkCreate(req.userId!, goalId, tasks);

    res.json(ApiResponse.success(savedTasks, 'Tasks generated by AI'));
  }),

  generatePlan: asyncHandler(async (req: AuthRequest, res: Response) => {
    const { date } = req.body;
    const user = await User.findById(req.userId!);
    const startTime = user?.preferences?.preferredStartTime || '09:00';
    const hoursPerDay = user?.preferences?.workingHoursPerDay || 8;
    const endHour = parseInt(startTime.split(':')[0]) + hoursPerDay;
    const endTime = `${endHour.toString().padStart(2, '0')}:00`;

    // Get all incomplete tasks, prioritizing ones scheduled for this date
    const tasks = await Task.find({
      user: req.userId!,
      status: { $ne: 'done' },
    })
      .populate('goal', 'title deadline')
      .sort({ priority: -1, order: 1 });

    if (tasks.length === 0) {
      res.json(ApiResponse.success({ schedule: [], notes: 'No tasks to schedule', totalMinutes: 0 }));
      return;
    }

    const plan = await aiService.generateDailyPlan(
      tasks,
      date,
      startTime,
      endTime,
      hoursPerDay
    );

    // Save plan to database
    if (plan.schedule && plan.schedule.length > 0) {
      const planTasks = plan.schedule.map((s: any) => ({
        task: s.taskId,
        startTime: s.startTime,
        endTime: s.endTime,
        completed: false,
      }));

      await plannerService.savePlan(req.userId!, date, {
        tasks: planTasks,
        totalPlannedMinutes: plan.totalMinutes || 0,
        aiNotes: plan.notes || '',
      });
    }

    res.json(ApiResponse.success(plan, 'Daily plan generated'));
  }),

  replan: asyncHandler(async (req: AuthRequest, res: Response) => {
    const { goalId } = req.body;
    const goal = await goalService.getById(goalId, req.userId!);
    const user = await User.findById(req.userId!);
    const hoursPerDay = user?.preferences?.workingHoursPerDay || 8;

    const allTasks = await Task.find({ goal: goalId, user: req.userId! });
    const missedTasks = allTasks.filter(
      (t) => t.status !== 'done' && t.scheduledDate && new Date(t.scheduledDate) < new Date()
    );
    const remainingTasks = allTasks.filter((t) => t.status !== 'done');

    const daysLeft = Math.ceil(
      (goal.deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)
    );

    const result = await aiService.replan(
      missedTasks.map((t) => ({ _id: t._id, title: t.title, priority: t.priority, estimatedMinutes: t.estimatedMinutes })),
      remainingTasks.map((t) => ({ _id: t._id, title: t.title, priority: t.priority, estimatedMinutes: t.estimatedMinutes })),
      goal.deadline.toISOString(),
      daysLeft,
      hoursPerDay
    );

    // Update task scheduled dates based on AI suggestions
    if (result.revisedSchedule) {
      for (const item of result.revisedSchedule) {
        await Task.findByIdAndUpdate(item.taskId, {
          scheduledDate: new Date(item.suggestedDate),
          priority: item.newPriority,
        });
      }
    }

    res.json(ApiResponse.success(result, 'Plan revised'));
  }),

  insights: asyncHandler(async (req: AuthRequest, res: Response) => {
    const userId = req.userId!;

    // Gather stats
    const taskStats = await taskService.getStats(userId);
    const weeklyStats = await plannerService.getWeeklyStats(userId);
    const goals = await Goal.find({ user: userId });
    const goalsCompleted = goals.filter((g) => g.status === 'completed').length;

    const result = await aiService.getInsights(
      taskStats.completedTasks,
      taskStats.todoTasks + taskStats.inProgressTasks,
      weeklyStats.totalPlanned > 0
        ? weeklyStats.totalCompleted / weeklyStats.totalPlanned
        : 1.0,
      goals.length,
      goalsCompleted,
      JSON.stringify(weeklyStats)
    );

    res.json(ApiResponse.success(result, 'Insights generated'));
  }),
};
